site_name: Synchronization-Tundra-Urho3D
site_url: https://synchronization-tundra-urho3d.readthedocs.org
repo_url: https://github.com/realXtend/tundra-urho3d
site_description: Synchronization Documentation
docs_dir: doc
site_dir: html
google_analytics: ['UA-84140266-1', 'synchronization-tundra-urho3d.readthedocs.io']
markdown_extensions: [toc,fenced_code]
use_directory_urls: false
theme: readthedocs
extra_css: ["https://fiware.org/style/fiware_readthedocs.css"]
pages:
  - Home: index.md
  - 'Installation and Administration guide': Installation_and_Administration_guide.md
  - 'User and Programmers guide': User_and_Programmers_guide.md
